apiVersion: v1
kind: Namespace
metadata:
  name: menu-scanner
  labels:
    name: menu-scanner
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: menu-scanner-config
  namespace: menu-scanner
data:
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  MEMCACHED_HOST: "memcached-service"
  MEMCACHED_PORT: "11211"
  ELASTICSEARCH_HOST: "elasticsearch-service"
  ELASTICSEARCH_PORT: "9200"
  GRPC_MENU_SERVICE_HOST: "menu-service"
  GRPC_MENU_SERVICE_PORT: "50051"
  GRPC_IMAGE_SERVICE_HOST: "image-service"
  GRPC_IMAGE_SERVICE_PORT: "50052"
